# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Firex.FirecrackerAPI.Model.BalloonUpdate do
  @moduledoc """
  Balloon device descriptor.
  """

  @derive [Poison.Encoder]
  defstruct [
    :amount_mib
  ]

  @type t :: %__MODULE__{
          :amount_mib => integer()
        }
end

defimpl Poison.Decoder, for: Firex.FirecrackerAPI.Model.BalloonUpdate do
  def decode(value, _options) do
    value
  end
end
