# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Firex.FirecrackerAPI.Model.BalloonStatsUpdate do
  @moduledoc """
  Update the statistics polling interval, with the first statistics update scheduled immediately. Statistics cannot be turned on/off after boot.
  """

  @derive [Poison.Encoder]
  defstruct [
    :stats_polling_interval_s
  ]

  @type t :: %__MODULE__{
          :stats_polling_interval_s => integer()
        }
end

defimpl Poison.Decoder, for: Firex.FirecrackerAPI.Model.BalloonStatsUpdate do
  def decode(value, _options) do
    value
  end
end
