# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Firex.FirecrackerAPI.Model.Balloon do
  @moduledoc """
  Balloon device descriptor.
  """

  @derive [Poison.Encoder]
  defstruct [
    :amount_mib,
    :deflate_on_oom,
    :stats_polling_interval_s
  ]

  @type t :: %__MODULE__{
          :amount_mib => integer(),
          :deflate_on_oom => boolean(),
          :stats_polling_interval_s => integer() | nil
        }
end

defimpl Poison.Decoder, for: Firex.FirecrackerAPI.Model.Balloon do
  def decode(value, _options) do
    value
  end
end
