# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Firex.FirecrackerAPI.Model.BalloonStats do
  @moduledoc """
  Describes the balloon device statistics.
  """

  @derive [Poison.Encoder]
  defstruct [
    :target_pages,
    :actual_pages,
    :target_mib,
    :actual_mib,
    :swap_in,
    :swap_out,
    :major_faults,
    :minor_faults,
    :free_memory,
    :total_memory,
    :available_memory,
    :disk_caches,
    :hugetlb_allocations,
    :hugetlb_failures
  ]

  @type t :: %__MODULE__{
          :target_pages => integer(),
          :actual_pages => integer(),
          :target_mib => integer(),
          :actual_mib => integer(),
          :swap_in => integer() | nil,
          :swap_out => integer() | nil,
          :major_faults => integer() | nil,
          :minor_faults => integer() | nil,
          :free_memory => integer() | nil,
          :total_memory => integer() | nil,
          :available_memory => integer() | nil,
          :disk_caches => integer() | nil,
          :hugetlb_allocations => integer() | nil,
          :hugetlb_failures => integer() | nil
        }
end

defimpl Poison.Decoder, for: Firex.FirecrackerAPI.Model.BalloonStats do
  def decode(value, _options) do
    value
  end
end
