# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Firex.FirecrackerAPI.Model.BootSource do
  @moduledoc """
  Boot source descriptor.
  """

  @derive [Poison.Encoder]
  defstruct [
    :boot_args,
    :initrd_path,
    :kernel_image_path
  ]

  @type t :: %__MODULE__{
          :boot_args => String.t() | nil,
          :initrd_path => String.t() | nil,
          :kernel_image_path => String.t()
        }
end

defimpl Poison.Decoder, for: Firex.FirecrackerAPI.Model.BootSource do
  def decode(value, _options) do
    value
  end
end
