# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Firex.FirecrackerAPI.Model.Drive do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :drive_id,
    :is_read_only,
    :is_root_device,
    :partuuid,
    :path_on_host,
    :rate_limiter
  ]

  @type t :: %__MODULE__{
          :drive_id => String.t(),
          :is_read_only => boolean(),
          :is_root_device => boolean(),
          :partuuid => String.t() | nil,
          :path_on_host => String.t(),
          :rate_limiter => Firex.FirecrackerAPI.Model.RateLimiter.t() | nil
        }
end

defimpl Poison.Decoder, for: Firex.FirecrackerAPI.Model.Drive do
  import Firex.FirecrackerAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:rate_limiter, :struct, Firex.FirecrackerAPI.Model.RateLimiter, options)
  end
end
