# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Firex.FirecrackerAPI.Model.InstanceInfo do
  @moduledoc """
  Describes MicroVM instance information.
  """

  @derive [Poison.Encoder]
  defstruct [
    :app_name,
    :id,
    :state,
    :vmm_version
  ]

  @type t :: %__MODULE__{
          :app_name => String.t(),
          :id => String.t(),
          :state => String.t(),
          :vmm_version => String.t()
        }
end

defimpl Poison.Decoder, for: Firex.FirecrackerAPI.Model.InstanceInfo do
  def decode(value, _options) do
    value
  end
end
