# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Firex.FirecrackerAPI.Model.InstanceActionInfo do
  @moduledoc """
  Variant wrapper containing the real action.
  """

  @derive [Poison.Encoder]
  defstruct [
    :action_type
  ]

  @type t :: %__MODULE__{
          :action_type => String.t()
        }
end

defimpl Poison.Decoder, for: Firex.FirecrackerAPI.Model.InstanceActionInfo do
  def decode(value, _options) do
    value
  end
end
