# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Firex.FirecrackerAPI.Model.MachineConfiguration do
  @moduledoc """
  Describes the number of vCPUs, memory size, Hyperthreading capabilities and the CPU template.
  """

  @derive [Poison.Encoder]
  defstruct [
    :cpu_template,
    :ht_enabled,
    :mem_size_mib,
    :track_dirty_pages,
    :vcpu_count
  ]

  @type t :: %__MODULE__{
          :cpu_template => Firex.FirecrackerAPI.Model.CpuTemplate.t() | nil,
          :ht_enabled => boolean(),
          :mem_size_mib => integer(),
          :track_dirty_pages => boolean() | nil,
          :vcpu_count => integer()
        }
end

defimpl Poison.Decoder, for: Firex.FirecrackerAPI.Model.MachineConfiguration do
  import Firex.FirecrackerAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:cpu_template, :struct, Firex.FirecrackerAPI.Model.CpuTemplate, options)
  end
end
