# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Firex.FirecrackerAPI.Model.Metrics do
  @moduledoc """
  Describes the configuration option for the metrics capability.
  """

  @derive [Poison.Encoder]
  defstruct [
    :metrics_path
  ]

  @type t :: %__MODULE__{
          :metrics_path => String.t()
        }
end

defimpl Poison.Decoder, for: Firex.FirecrackerAPI.Model.Metrics do
  def decode(value, _options) do
    value
  end
end
