# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Firex.FirecrackerAPI.Model.MmdsConfig do
  @moduledoc """
  Defines the MMDS configuration.
  """

  @derive [Poison.Encoder]
  defstruct [
    :ipv4_address
  ]

  @type t :: %__MODULE__{
          :ipv4_address => String.t() | nil
        }
end

defimpl Poison.Decoder, for: Firex.FirecrackerAPI.Model.MmdsConfig do
  def decode(value, _options) do
    value
  end
end
