# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Firex.FirecrackerAPI.Model.PartialDrive do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :drive_id,
    :path_on_host,
    :rate_limiter
  ]

  @type t :: %__MODULE__{
          :drive_id => String.t(),
          :path_on_host => String.t() | nil,
          :rate_limiter => Firex.FirecrackerAPI.Model.RateLimiter.t() | nil
        }
end

defimpl Poison.Decoder, for: Firex.FirecrackerAPI.Model.PartialDrive do
  import Firex.FirecrackerAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:rate_limiter, :struct, Firex.FirecrackerAPI.Model.RateLimiter, options)
  end
end
