# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Firex.FirecrackerAPI.Model.SnapshotCreateParams do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :mem_file_path,
    :snapshot_path,
    :snapshot_type,
    :version
  ]

  @type t :: %__MODULE__{
          :mem_file_path => String.t(),
          :snapshot_path => String.t(),
          :snapshot_type => String.t() | nil,
          :version => String.t() | nil
        }
end

defimpl Poison.Decoder, for: Firex.FirecrackerAPI.Model.SnapshotCreateParams do
  def decode(value, _options) do
    value
  end
end
