# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Firex.FirecrackerAPI.Model.SnapshotLoadParams do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :enable_diff_snapshots,
    :mem_file_path,
    :snapshot_path,
    :resume_vm
  ]

  @type t :: %__MODULE__{
          :enable_diff_snapshots => boolean() | nil,
          :mem_file_path => String.t(),
          :snapshot_path => String.t(),
          :resume_vm => boolean() | nil
        }
end

defimpl Poison.Decoder, for: Firex.FirecrackerAPI.Model.SnapshotLoadParams do
  def decode(value, _options) do
    value
  end
end
