# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Firex.FirecrackerAPI.Model.Vm do
  @moduledoc """
  Defines the microVM running state. It is especially useful in the snapshotting context.
  """

  @derive [Poison.Encoder]
  defstruct [
    :state
  ]

  @type t :: %__MODULE__{
          :state => String.t()
        }
end

defimpl Poison.Decoder, for: Firex.FirecrackerAPI.Model.Vm do
  def decode(value, _options) do
    value
  end
end
