# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Firex.FirecrackerAPI.Model.Vsock do
  @moduledoc """
  Defines a vsock device, backed by a set of Unix Domain Sockets, on the host side. For host-initiated connections, Firecracker will be listening on the Unix socket identified by the path `uds_path`. Firecracker will create this socket, bind and listen on it. Host-initiated connections will be performed by connection to this socket and issuing a connection forwarding request to the desired guest-side vsock port (i.e. `CONNECT 52\\n`, to connect to port 52). For guest-initiated connections, Firecracker will expect host software to be bound and listening on Unix sockets at `uds_path_<PORT>`. E.g. \"/path/to/host_vsock.sock_52\" for port number 52.
  """

  @derive [Poison.Encoder]
  defstruct [
    :guest_cid,
    :uds_path,
    :vsock_id
  ]

  @type t :: %__MODULE__{
          :guest_cid => integer(),
          :uds_path => String.t(),
          :vsock_id => String.t()
        }
end

defimpl Poison.Decoder, for: Firex.FirecrackerAPI.Model.Vsock do
  def decode(value, _options) do
    value
  end
end
